name: Run Java tests on Linux

on:
    push:
      branches:
        - main

    pull_request:
      branches:
        - main

    schedule:
      - cron: '30 5 * * 1'

    workflow_dispatch:

permissions:
  contents: write
#  pages: write
#  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run tests via Maven with integrated Allure
        run: mvn clean test

      - name: Create Allure environment information
        if: always()
        shell: bash
        run: |
          mkdir -p target/allure-results

          JAVA_VERSION=$(java -version 2>&1 | head -n 1)

          cat > target/allure-results/environment.properties <<EOF
          Execution=GitHub Actions
          OS=Linux
          Java=${JAVA_VERSION}
          Browser=Chrome
          Repository=${GITHUB_REPOSITORY}
          Branch=${GITHUB_REF_NAME}
          Run.Number=${GITHUB_RUN_NUMBER}
          Workflow=${GITHUB_WORKFLOW}
          EOF

      - name: Load Allure History
        uses: actions/checkout@v5
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

#      - name: Upload Allure Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results
#          path: target/allure-results

      - name: Generate Allure Report
        if: always()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Publish Allure Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history

#      - name: Setup GitHub Pages
#        if: always()
#        uses: actions/configure-pages@v5
#
#      - name: Upload Allure Report
#        if: always()
#        uses: actions/upload-pages-artifact@v4
#        with:
#          path: allure-report

#  deploy:
#    needs: test
#    if: always()
#
#    permissions:
#      contents: read
#      pages: write
#      id-token: write
#
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Deploy Allure Report to GitHub Pages
#      id: deployment
#      uses: actions/deploy-pages@v4