name: Run Java tests on Linux

on:
    push:
    workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Run tests via Maven with integrated Allure
        run: mvn clean test

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
            name: allure-results
            path: target/allure-results
